branches:
  only:
    - master
    - gh-pages

language: node_js

node_js:
  - "0.10"

before_install:
  - gem install jekyll
  - gem install rouge
  - npm install -g grunt-cli

script: "grunt test"

git:
  depth: 10
